services:
  client:
    build:
      context: ./Client
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    volumes:
      - ./Server:/app
    environment:
      - NODE_ENV=development
